name: Build and Upload Windows Package

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date suffix (optional)"
        required: false
        default: ""

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        torch_cuda: [cu126, cu128]
    env:
      TORCH_CUDA: ${{ matrix.torch_cuda }}
      MODELSCOPE_USERNAME: ${{ secrets.MODELSCOPE_USERNAME }}
      MODELSCOPE_TOKEN: ${{ secrets.MODELSCOPE_TOKEN }}
      DATE: ${{ github.event.inputs.date }}
      GITHUB_REPOSITORY: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: c:\users\runneradmin\appdata\local\pip\cache
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run Build and Upload Script
        shell: pwsh
        run: |
          Move-Item .github/build_windows_packages.ps1 ../build_windows_packages.ps1
          ../build_windows_packages.ps1